apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejemplo-angular
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: ejemplo-angular
        image: mndzdocker/ejemplo-angular:latest
---
apiVersion: v1
kind: Service
metadata:
  name: ejemplo-angular
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001


