apiVersion: v1
kind: Deployment
metadata:
  name: app-angular
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-ang
    spec:
      containers:
      - name: app-ang
        image: mndzdocker/app_angular
        ports:
        - containerPort: 80