---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: mndzdocker/app_angular:tagname
          ports:
            - containerPort: 80
